propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native

  entity:
    id:             ~
    name:           { type: varchar, size: '255', required: true }
    value:          { type: integer, size: '11', required: true, default: 0 }
    nb_day:         { type: integer, size: '11', required: true, default: 0 }
    history:        { type: longvarchar, required: true }
    created_at:     ~
    updated_at:     ~
